# Generated by Django 6.0.2 on 2026-02-17 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_datetime', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bsa', models.FloatField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AorticValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psk', models.FloatField(blank=True, null=True)),
                ('grad_max', models.FloatField(blank=True, null=True)),
                ('grad_mean', models.FloatField(blank=True, null=True)),
                ('regurgitation', models.IntegerField(default=0)),
                ('area', models.FloatField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Aorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('valve_opening', models.FloatField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='LeftVentricle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivsd', models.FloatField(blank=True, null=True)),
                ('edd', models.FloatField(blank=True, null=True)),
                ('esd', models.FloatField(blank=True, null=True)),
                ('pw', models.FloatField(blank=True, null=True)),
                ('edv', models.FloatField(blank=True, null=True)),
                ('esv', models.FloatField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='MitralValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.FloatField(blank=True, null=True)),
                ('a', models.FloatField(blank=True, null=True)),
                ('grad_max', models.FloatField(blank=True, null=True)),
                ('dte', models.FloatField(blank=True, null=True)),
                ('ivrt', models.FloatField(blank=True, null=True)),
                ('reg', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='MyocardialSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.PositiveSmallIntegerField()),
                ('state', models.PositiveSmallIntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='OtherChambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la', models.FloatField(blank=True, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('rv', models.FloatField(blank=True, null=True)),
                ('lav', models.FloatField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PulmonaryArtery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('grad_max', models.FloatField(blank=True, null=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('at', models.FloatField(blank=True, null=True)),
                ('et', models.FloatField(blank=True, null=True)),
                ('reg', models.IntegerField(default=0)),
                ('ivc', models.FloatField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
        migrations.CreateModel(
            name='TricuspidValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.FloatField(blank=True, null=True)),
                ('a', models.FloatField(blank=True, null=True)),
                ('grad_max', models.FloatField(blank=True, null=True)),
                ('tapse', models.FloatField(blank=True, null=True)),
                ('reg', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.examination')),
            ],
        ),
    ]
